### PR TITLE
make creation of exchange, queue & binding configurable

### PR DESCRIPTION
**Pull request by hartmut-ltd**
added default config for backwards compatibility

### CODE REVIEW

**Comment by vladimir-yuldashev** [comment]
Good job. I will go through it and test later. Did you fully test this feature?

**Comment by moominpapa** [comment]
Yes, it has been tested. Please keep me updated if there are any issues.

**Comment by hartmut-ltd** [comment]
Hi, any issues or change requests on your side?

**Comment by vladimir-yuldashev** [comment]
Merged and released in 5.1

**Pull request merged**
