### PR TITLE
v5.1: get it working for lumen 5.1

### PR DESCRIPTION
**Pull request by ha-quidco**
Hi, 

I had to change things slightly for Illuminate compliance to get this package working with lumen 5.1.

I would highly appreciate to get this reviewed, merged and provided as e.g. 5.1.1 with the main repository / composer asap.

Thanks
Hartmut

### CODE REVIEW

**Comment by vladimir-yuldashev** [comment]
Please revert your changes in "composer.json" and I will merge your pull request.

**Comment by ha-quidco** [comment]
Hi Vladimir,

Thanks for coming back on me!
My apologies, I thought I've created that pull request on that specific initial commit only...

Will revert that commit now.

**Comment by ha-quidco** [comment]
done.

**Comment by vladimir-yuldashev** [comment]
Merged and added to version 5.1. Thank you for your contribution.

**Comment by ha-quidco** [comment]
Thanks a lot! You're welcome.

**Pull request merged**
